const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const defaultAiModulePython = process.platform === 'win32'
  ? path.join(projectRoot, 'ai_module', 'venv', 'Scripts', 'python.exe')
  : path.join(projectRoot, 'ai_module', 'venv', 'bin', 'python');
const aiModulePython = process.env.AI_MODULE_PYTHON || defaultAiModulePython;
const hanoiProxyPython = process.env.HANOI_PROXY_PYTHON || aiModulePython;

module.exports = {
  apps: [
    {
      name: 'smart-alert-api',
      script: './src/server.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
        DISABLE_REDIS: 'true',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        DISABLE_REDIS: 'true',
        ALERT_CLEAR_HEARTBEATS: '3',
        EVENT_IMAGE_STORAGE: 'active',
        EVENT_RETENTION_DAYS: '7',
        HANOI_PROXY_AUTOSTART: 'false',
        HANOI_MJPEG_PROXY_BASE_URL: 'http://127.0.0.1:5001',
        AI_DETECTOR_URL: 'http://127.0.0.1:5055/detect',
        SCANNER_AUTOSTART: 'true',
        SCANNER_CAMERA_SOURCE: 'hcm',
        SCANNER_CAMERA_LIMIT: '40',
        SCANNER_CONCURRENCY: '3',
        SCANNER_INTERVAL_MS: '10000',
        SCANNER_FRAME_TIMEOUT_MS: '8000',
        SCANNER_DETECT_TIMEOUT_MS: '20000',
        SCANNER_FAILURE_COOLDOWN_MS: '60000',
        SCANNER_STALE_TARGET_MS: '300000',
      },
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/error.log',
      out_file: './logs/out.log',
      merge_logs: true,
      watch: false,
    },
    {
      name: 'hanoi-wss-proxy',
      cwd: '..',
      script: './ai_module/hanoi_wss_proxy.py',
      interpreter: hanoiProxyPython,
      instances: 1,
      exec_mode: 'fork',
      env: {
        HANOI_PROXY_HOST: '127.0.0.1',
        HANOI_PROXY_PORT: '5001',
        HANOI_PROXY_FPS: '5',
        HANOI_PROXY_JPEG_QUALITY: '5',
        HANOI_PROXY_IDLE_SECONDS: '90',
        HANOI_PROXY_STALE_SECONDS: '20',
        HANOI_CAMERA_CACHE_FILE: './backend/hanoi_cameras.json',
      },
      env_production: {
        HANOI_PROXY_HOST: '127.0.0.1',
        HANOI_PROXY_PORT: '5001',
        HANOI_PROXY_FPS: '5',
        HANOI_PROXY_JPEG_QUALITY: '5',
        HANOI_PROXY_IDLE_SECONDS: '90',
        HANOI_PROXY_STALE_SECONDS: '20',
        HANOI_CAMERA_CACHE_FILE: './backend/hanoi_cameras.json',
      },
      max_memory_restart: '600M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './backend/logs/hanoi-proxy-error.log',
      out_file: './backend/logs/hanoi-proxy-out.log',
      merge_logs: true,
      watch: false,
      autorestart: true,
      restart_delay: 3000,
    },
    {
      name: 'ai-detector-api',
      cwd: '..',
      script: './ai_module/detector_api.py',
      interpreter: aiModulePython,
      instances: 1,
      exec_mode: 'fork',
      env: {
        DETECTOR_HOST: '127.0.0.1',
        DETECTOR_PORT: '5055',
        DETECTOR_ENABLE_YOLO: 'true',
        DETECTOR_YOLO_WEIGHTS: './ai_module/yolo26x.pt',
        DETECTOR_YOLO_FALLBACK_WEIGHTS: './ai_module/yolov8m.pt',
        DETECTOR_YOLO_IMG_SIZE: '640',
        DETECTOR_YOLO_ENABLE_SLICES: 'false',
        DETECTOR_ENABLE_FIRE_YOLO: 'true',
        DETECTOR_FIRE_YOLO_WEIGHTS: './ai_module/fire_smoke_yolov8n.pt',
        DETECTOR_FIRE_YOLO_CONF: '0.50',
        DETECTOR_FIRE_YOLO_IOU: '0.45',
        DETECTOR_FIRE_YOLO_IMG_SIZE: '640',
        DETECTOR_FIRE_YOLO_MIN_BOX_AREA_RATIO: '0.004',
        DETECTOR_FIRE_REQUIRE_AI_VERIFICATION: 'true',
        DETECTOR_FIRE_ALLOW_LOCAL_FALLBACK: 'false',
        DETECTOR_AI_FIRE_MIN_CONFIDENCE: '0.75',
        DETECTOR_FLOOD_REQUIRE_AI_VERIFICATION: 'true',
        DETECTOR_FLOOD_ALLOW_LOCAL_FALLBACK: 'false',
        DETECTOR_AI_FLOOD_MIN_CONFIDENCE: '0.80',
        DETECTOR_AI_PROVIDER: 'groq',
        DETECTOR_AI_ENDPOINT: 'https://api.groq.com/openai/v1/chat/completions',
        DETECTOR_AI_MODEL: 'meta-llama/llama-4-scout-17b-16e-instruct',
        GROQ_VISION_MODEL: 'meta-llama/llama-4-scout-17b-16e-instruct',
        DETECTOR_AI_ENABLED: 'true',
        DETECTOR_AI_RATE_LIMIT_PER_MIN: '30',
        DETECTOR_OPENCV_INCIDENT_FALLBACK: 'false',
        DETECTOR_OPENCV_FIRE_SAFETY_NET: 'false',
        DETECTOR_STRONG_FIRE_RATIO: '0.08',
        DETECTOR_FLOOD_WATCH_RATIO: '0.30',
        DETECTOR_FLOOD_ALERT_RATIO: '0.48',
        DETECTOR_FLOOD_MIN_LARGEST_BLOB_RATIO: '0.16',
        DETECTOR_FLOOD_MIN_BOTTOM_COVERAGE: '0.30',
      },
      env_production: {
        DETECTOR_HOST: '127.0.0.1',
        DETECTOR_PORT: '5055',
        DETECTOR_ENABLE_YOLO: 'true',
        DETECTOR_YOLO_WEIGHTS: './ai_module/yolo26x.pt',
        DETECTOR_YOLO_FALLBACK_WEIGHTS: './ai_module/yolov8m.pt',
        DETECTOR_YOLO_IMG_SIZE: '640',
        DETECTOR_YOLO_ENABLE_SLICES: 'false',
        DETECTOR_ENABLE_FIRE_YOLO: 'true',
        DETECTOR_FIRE_YOLO_WEIGHTS: './ai_module/fire_smoke_yolov8n.pt',
        DETECTOR_FIRE_YOLO_CONF: '0.50',
        DETECTOR_FIRE_YOLO_IOU: '0.45',
        DETECTOR_FIRE_YOLO_IMG_SIZE: '640',
        DETECTOR_FIRE_YOLO_MIN_BOX_AREA_RATIO: '0.004',
        DETECTOR_FIRE_REQUIRE_AI_VERIFICATION: 'true',
        DETECTOR_FIRE_ALLOW_LOCAL_FALLBACK: 'false',
        DETECTOR_AI_FIRE_MIN_CONFIDENCE: '0.75',
        DETECTOR_FLOOD_REQUIRE_AI_VERIFICATION: 'true',
        DETECTOR_FLOOD_ALLOW_LOCAL_FALLBACK: 'false',
        DETECTOR_AI_FLOOD_MIN_CONFIDENCE: '0.80',
        DETECTOR_AI_PROVIDER: 'groq',
        DETECTOR_AI_ENDPOINT: 'https://api.groq.com/openai/v1/chat/completions',
        DETECTOR_AI_MODEL: 'meta-llama/llama-4-scout-17b-16e-instruct',
        GROQ_VISION_MODEL: 'meta-llama/llama-4-scout-17b-16e-instruct',
        DETECTOR_AI_ENABLED: 'true',
        DETECTOR_AI_RATE_LIMIT_PER_MIN: '30',
        DETECTOR_OPENCV_INCIDENT_FALLBACK: 'false',
        DETECTOR_OPENCV_FIRE_SAFETY_NET: 'false',
        DETECTOR_STRONG_FIRE_RATIO: '0.08',
        DETECTOR_FLOOD_WATCH_RATIO: '0.30',
        DETECTOR_FLOOD_ALERT_RATIO: '0.48',
        DETECTOR_FLOOD_MIN_LARGEST_BLOB_RATIO: '0.16',
        DETECTOR_FLOOD_MIN_BOTTOM_COVERAGE: '0.30',
      },
      max_memory_restart: '900M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './backend/logs/ai-detector-error.log',
      out_file: './backend/logs/ai-detector-out.log',
      merge_logs: true,
      watch: false,
      autorestart: true,
      restart_delay: 3000,
    },
  ],
};
