module.exports = {
  apps: [
    {
      name: 'smart-alert-api',
      script: './src/server.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        HANOI_PROXY_AUTOSTART: 'false',
        HANOI_MJPEG_PROXY_BASE_URL: 'http://127.0.0.1:5001',
      },
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/error.log',
      out_file: './logs/out.log',
      merge_logs: true,
      watch: false,
    },
    {
      name: 'hanoi-wss-proxy',
      cwd: '..',
      script: './ai_module/hanoi_wss_proxy.py',
      interpreter: process.env.HANOI_PROXY_PYTHON || './ai_module/venv/bin/python',
      instances: 1,
      exec_mode: 'fork',
      env: {
        HANOI_PROXY_HOST: '127.0.0.1',
        HANOI_PROXY_PORT: '5001',
        HANOI_PROXY_FPS: '8',
        HANOI_PROXY_JPEG_QUALITY: '5',
        HANOI_PROXY_IDLE_SECONDS: '90',
        HANOI_PROXY_STALE_SECONDS: '20',
        HANOI_CAMERA_CACHE_FILE: './backend/hanoi_cameras.json',
      },
      env_production: {
        HANOI_PROXY_HOST: '127.0.0.1',
        HANOI_PROXY_PORT: '5001',
        HANOI_PROXY_FPS: '8',
        HANOI_PROXY_JPEG_QUALITY: '5',
        HANOI_PROXY_IDLE_SECONDS: '90',
        HANOI_PROXY_STALE_SECONDS: '20',
        HANOI_CAMERA_CACHE_FILE: './backend/hanoi_cameras.json',
      },
      max_memory_restart: '600M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './backend/logs/hanoi-proxy-error.log',
      out_file: './backend/logs/hanoi-proxy-out.log',
      merge_logs: true,
      watch: false,
      autorestart: true,
      restart_delay: 3000,
    },
  ],
};
