module.exports = {
  apps: [
    {
      name: 'smart-alert-api',
      script: './src/server.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        ALERT_CLEAR_HEARTBEATS: '3',
        EVENT_IMAGE_STORAGE: 'active',
        EVENT_RETENTION_DAYS: '7',
        HANOI_PROXY_AUTOSTART: 'false',
        HANOI_MJPEG_PROXY_BASE_URL: 'http://127.0.0.1:5001',
        AI_DETECTOR_URL: 'http://127.0.0.1:5055/detect',
        SCANNER_AUTOSTART: 'true',
        SCANNER_CAMERA_SOURCE: 'all',
        SCANNER_CAMERA_LIMIT: '80',
        SCANNER_CONCURRENCY: '8',
        SCANNER_INTERVAL_MS: '1000',
        SCANNER_FRAME_TIMEOUT_MS: '8000',
        SCANNER_DETECT_TIMEOUT_MS: '20000',
        SCANNER_FAILURE_COOLDOWN_MS: '60000',
        SCANNER_STALE_TARGET_MS: '300000',
      },
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/error.log',
      out_file: './logs/out.log',
      merge_logs: true,
      watch: false,
    },
    {
      name: 'hanoi-wss-proxy',
      cwd: '..',
      script: './ai_module/hanoi_wss_proxy.py',
      interpreter: process.env.AI_MODULE_PYTHON || process.env.HANOI_PROXY_PYTHON || './ai_module/venv/bin/python',
      instances: 1,
      exec_mode: 'fork',
      env: {
        HANOI_PROXY_HOST: '127.0.0.1',
        HANOI_PROXY_PORT: '5001',
        HANOI_PROXY_FPS: '8',
        HANOI_PROXY_JPEG_QUALITY: '5',
        HANOI_PROXY_IDLE_SECONDS: '90',
        HANOI_PROXY_STALE_SECONDS: '20',
        HANOI_CAMERA_CACHE_FILE: './backend/hanoi_cameras.json',
      },
      env_production: {
        HANOI_PROXY_HOST: '127.0.0.1',
        HANOI_PROXY_PORT: '5001',
        HANOI_PROXY_FPS: '8',
        HANOI_PROXY_JPEG_QUALITY: '5',
        HANOI_PROXY_IDLE_SECONDS: '90',
        HANOI_PROXY_STALE_SECONDS: '20',
        HANOI_CAMERA_CACHE_FILE: './backend/hanoi_cameras.json',
      },
      max_memory_restart: '600M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './backend/logs/hanoi-proxy-error.log',
      out_file: './backend/logs/hanoi-proxy-out.log',
      merge_logs: true,
      watch: false,
      autorestart: true,
      restart_delay: 3000,
    },
    {
      name: 'ai-detector-api',
      cwd: '..',
      script: './ai_module/detector_api.py',
      interpreter: process.env.AI_MODULE_PYTHON || './ai_module/venv/bin/python',
      instances: 1,
      exec_mode: 'fork',
      env: {
        DETECTOR_HOST: '127.0.0.1',
        DETECTOR_PORT: '5055',
        DETECTOR_ENABLE_YOLO: 'true',
        DETECTOR_YOLO_WEIGHTS: 'yolov8n.pt',
        DETECTOR_YOLO_FALLBACK_WEIGHTS: 'yolov8m.pt',
        DETECTOR_YOLO_IMG_SIZE: '640',
        DETECTOR_YOLO_ENABLE_SLICES: 'false',
        DETECTOR_GROQ_ENABLED: 'false',
      },
      env_production: {
        DETECTOR_HOST: '127.0.0.1',
        DETECTOR_PORT: '5055',
        DETECTOR_ENABLE_YOLO: 'true',
        DETECTOR_YOLO_WEIGHTS: 'yolov8n.pt',
        DETECTOR_YOLO_FALLBACK_WEIGHTS: 'yolov8m.pt',
        DETECTOR_YOLO_IMG_SIZE: '640',
        DETECTOR_YOLO_ENABLE_SLICES: 'false',
        DETECTOR_GROQ_ENABLED: 'false',
      },
      max_memory_restart: '900M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './backend/logs/ai-detector-error.log',
      out_file: './backend/logs/ai-detector-out.log',
      merge_logs: true,
      watch: false,
      autorestart: true,
      restart_delay: 3000,
    },
  ],
};
